#!/usr/bin/python

import unittest
from memorize_flashcards.policy import Card, CardException, EmptyCardException

class TestCard(unittest.TestCase):
	def test_empty(self):
		with self.assertRaises(EmptyCardException):
			card = Card(12345, '/dev/null', '-', '-')

if __name__ == '__main__':
	unittest.main()
